[radartutorial]
adapter = "pipelines.sources.radartutorial:Radartutorial"

[deagel]
adapter = "pipelines.sources.deagel:Deagel"

[virtualglobetrotting]
adapter = "pipelines.sources.virtualglobetrotting:VirtualGlobetrotting"

[russianforces]
adapter = "pipelines.sources.russianforces:RussianForces"
