[radartutorial]
adapter = "pipelines.sources.radartutorial:Radartutorial"

[deagel]
adapter = "pipelines.sources.deagel:Deagel"

[virtualglobetrotting]
adapter = "pipelines.sources.virtualglobetrotting:VirtualGlobetrotting"

[russianforces]
adapter = "pipelines.sources.russianforces:RussianForces"

[wikipedia]
adapter = "pipelines.sources.wikipedia:Wikipedia"

[commons]
adapter = "pipelines.sources.commons:Commons"

[armyrecognition]
adapter = "pipelines.sources.armyrecognition:ArmyRecognition"

[fandom]
adapter = "pipelines.sources.fandom:Fandom"

[climateviewer]
adapter = "pipelines.sources.climateviewer:ClimateViewer"
